sudo: required
language: java
jdk: oraclejdk8
services: mongodb
before_install:
  - npm install typings -g
  - cd server
  - mvn -N io.takari:maven:wrapper
after_success:
  - mvn clean verify -P test jacoco:prepare-agent jacoco:report coveralls:report
