sudo: required
language: java
jdk: oraclejdk8
services: mongodb
before_install:
  - mvn -N io.takari:maven:wrapper
after_success:
  - mvn clean test -P test jacoco:prepare-agent jacoco:report coveralls:report
