spring:
  data:
    mongodb:
      uri: @mongodb.uri@
  social:
    twitter:
      app-id: lwiBGQ7pkItjZkfeYWONOEmZy
      app-secret: Hsph271KohkmOPLm30cbPakdPfjrweQF9Udw0WP7d6nR1zXjIE
    facebook:
      app-id: 110570572950923
      app-secret: 493a29907f64c3b9dba5abdc71adac41
    linkedin:
      app-id: 7866fl49abcya5
      app-secret: fFEq66FckiZtJYT5

server:
  port: 8080

storage:
  path: data/test-images

security:
  token:
    secret:
      key: Asjfwol2asf123142Ags1k23hnSA36as6f4qQ324FEsvb

git:
  apiUrl: https://api.github.com
  accessToken: ${GIT_ACCESS_TOKEN}