spring:
  data:
    mongodb:
      uri: @mongodb.uri@

server:
  port: 8080

storage:
  path: temp/test-files

security:
  token:
    secret:
      key: Asjfwol2asf123142Ags1k23hnSA36as6f4qQ324FEsvb

git:
  apiUrl: https://api.github.com
  accessToken: ${GIT_ACCESS_TOKEN}